version: '3.9'

services:
  postgres:
    container_name: postgres-pam
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tivon1234
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    networks:
      - academia
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  AppDocker:
    container_name: academianovit
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/pamela-guevara/academianovit:1.0.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    pull_policy: always
    networks:
      - academia
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=admin;Username=admin;Password=tivon1234

networks:
  academia:
    external: true
