name: GH-docker-registry-DEV
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academianovit:1.0.0
    - name: Login Registry
      run: docker login ghcr.io -u ${{ secrets.USERNAME_GH }} -p ${{ secrets.PAT_GH }}
    - name: Build the Docker retag image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ secrets.USERNAME_GH }}/academianovit:1.0.0
    - name: Upload image to Registry
      run: docker push ghcr.io/${{ secrets.USERNAME_GH }}/academianovit:1.0.0
